---
galaxy_info:
  author: Radimir Mikhailov
  description: Install HashiCorp products
  license: MIT
  role_name: hashicorp

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs:
  main:
    options:
      packages:
        description: Список пакетов
        required: true
        type: list
        elements: str
