---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_distribution is not defined

- name: Установить Snap-пакет приложения
  community.general.snap:
    name: zoom-client
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Для Fedora
  become: true
  when: ansible_distribution == 'Fedora'
  block:

    - name: Включить Flatpak-репозиторий Flathub
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present

    - name: Установить Flatpak-пакет приложения
      community.general.flatpak:
        name: us.zoom.Zoom
        remote: flathub
        state: present
