# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

export FZF_DEFAULT_OPTS='{{ default_options }}'
export FZF_DEFAULT_COMMAND='{{ default_command }}'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
