# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

set -gx FZF_DEFAULT_OPTS '{{ default_options }}'
set -gx FZF_DEFAULT_COMMAND '{{ default_command }}'
set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
