---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_user_dir is not defined

- name: Установить зависимости | sshpass
  ansible.builtin.package:
    name: sshpass
    state: present
  become: true

  # https://github.com/kislyuk/yq
- name: Установить зависимости | yq
  community.general.pipx:
    name: yq
    state: present

- name: Создать служебные подкаталоги в домашнем каталоге пользователя
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ item.value }}'
    state: directory
    mode: 0750
  loop: '{{ _subdirs | dict2items }}'

- name: Создать каталог для профилей соединений {{ connections_dir }}
  ansible.builtin.file:
    path: '{{ connections_dir }}'
    state: directory
    mode: 0750

- name: Создать/обновить конфигурационный файл скрипта
  ansible.builtin.copy:
    content: |
      # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
      # #  Managed by Ansible                                                     # #
      # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
      # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

      XSSH_CONNECTIONS_DIR={{ connections_dir }}
    dest: '{{ ansible_user_dir }}/{{ _subdirs.config }}/xssh.conf'
    mode: 0644

- name: Установить последнюю версию скрипта из GitHub-репозитория
  ansible.builtin.include_role:
    name: radimih.github_latest
  vars:
    user: radimih
    repo: xssh
    asset_filename_ending: xssh
    dest_binary: '{{ ansible_user_dir }}/{{ _subdirs.binary }}/xssh'

- name: Сконфигурировать XDG Desktop Entry для скрипта
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=xssh
      Exec={{ _subdirs.binary }}/xssh
      Type=Application
      Terminal=true
      Icon=utilities-terminal
      Comment=Manage SSH connections
      Categories=ConsoleOnly;
    dest: '{{ ansible_user_dir }}/{{ _subdirs.launcher }}/xssh.desktop'
  notify: update-desktop-database
