---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Установить пакет ansible-lint (для RedHat-семейства дистрибутивов)
  ansible.builtin.dnf:
    name: ansible-lint
    state: present
  become: true
  when: ansible_os_family | lower == 'redhat'

- name: Установить пакет ansible-lint
  community.general.pipx:
    name: ansible-lint
    state: present
  when: ansible_os_family | lower != 'redhat'
