---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_user_dir is not defined

- name: Установить Snap-пакет приложения
  community.general.snap:
    name: remmina
    state: present
  become: true

- name: Запустить приложение, чтобы оно создало свои каталоги и файлы
  ansible.builtin.command: remmina --version
  changed_when: false

- name: Создать каталог для хранения файлов-профилей соединений Remmina
  ansible.builtin.file:
    path: '{{ connections_dir }}'
    mode: 0755
    state: directory

- name: Установить в параметрах приложения каталог для профилей соединений в '{{ connections_dir }}'
  community.general.ini_file:
    path: '{{ _config_file }}'
    mode: 0600
    no_extra_spaces: true
    section: '{{ _config_section }}'
    option: datadir_path
    value: '{{ connections_dir }}'

- name: Установить в параметрах приложения secret приложения
  community.general.ini_file:
    path: '{{ _config_file }}'
    mode: 0600
    no_extra_spaces: true
    section: '{{ _config_section }}'
    option: secret
    value: '{{ secret }}'
  when: secret is defined

- name: Установить параметры приложения
  community.general.ini_file:
    path: '{{ _config_file }}'
    mode: 0600
    no_extra_spaces: true
    section: '{{ _config_section }}'
    option: '{{ item.key }}'
    value: '{{ item.value | string }}'
  loop: '{{ options | dict2items }}'
