---
- name: Установить пакет zsh, если еще не установлен
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Определить местонахождение бинарника zsh
  ansible.builtin.command: which zsh
  register: r__which_result
  ignore_errors: true
  changed_when: false

- name: Установить zsh shell-оболочкой по-умолчанию
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: '{{ r__which_result.stdout }}'
  become: true
  when: r__which_result.rc == 0

- name: Скопировать файлы настроек zsh
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: '{{ ansible_user_dir }}'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    mode: 0644
  loop:
    - .zshrc
    - .zshenv
