---
- name: Установить пакет zsh, если еще не установлен
  become: yes
  package:
    name: zsh
    state: present

- name: Определить местонахождение бинарника zsh
  command: which zsh
  register: which_result
  ignore_errors: yes
  changed_when: false

- name: Установить zsh shell-оболочкой по-умолчанию
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ which_result.stdout }}"
  when: which_result.rc == 0

- name: Скопировать файлы настроек zsh
  copy:
    src: files/
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0644"
