---
- name: Установить git, если еще не установлен
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Создать каталог установки менеджера плагинов
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ zsh_home_subdir }}/{{ _pm_home_subdir }}'
    state: directory
    mode: 0755

- name: Склонировать/обновить менеджер плагинов  # noqa: latest (предотвратить срабатывание правила latest[git] Ansible-линтера)
  ansible.builtin.git:
    repo: '{{ _pm_git_url }}'
    dest: '{{ ansible_user_dir }}/{{ zsh_home_subdir }}/{{ _pm_home_subdir }}'
    depth: 1
    force: true
    update: true
