---
- name: Установить пакет приложения
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Определить местонахождение бинарника zsh
  ansible.builtin.command: which zsh
  register: r__which_result
  ignore_errors: true
  changed_when: false

- name: Установить zsh shell-оболочкой по-умолчанию
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: '{{ r__which_result.stdout }}'
  become: true
  when: r__which_result.rc == 0

- name: Создать в домашнем каталоге служебные подкаталоги для zsh
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ item }}'
    state: directory
    mode: 0750
  loop:
    - '{{ zsh_home_subdir }}'
    - '{{ zsh_home_subdir }}/{{ _zshrc_subdir }}'

- name: Настроить стартовый файл ~/.zshenv
  ansible.builtin.copy:
    content: |
      # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
      # #  Managed by Ansible                                                     # #
      # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
      # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

      # .zshenv - Zsh environment file, загружается всегда

      export ZDOTDIR=~/{{ zsh_home_subdir }}
      export ZSHRC_DIR=$ZDOTDIR/{{ _zshrc_subdir }}
      [[ -f $ZDOTDIR/.zshenv ]] && . $ZDOTDIR/.zshenv || true
    dest: '{{ ansible_user_dir }}/.zshenv'
    mode: 0644

- name: Сформировать файлы настроек zsh
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: '{{ ansible_user_dir }}/{{ zsh_home_subdir }}/{{ item }}'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    mode: 0644
  loop:
    - .zshrc
    - .zshenv
