---
- name: Установить zsh
  import_tasks: install-zsh.yml

- name: Установить zinit
  import_tasks: install-zinit.yml

- name: Настроить Powerlevel10k
  import_tasks: setup-p10k.yml
  when: "'romkatv/powerlevel10k' in zinit_plugins|map(attribute='name')"
