---
- name: Установить zsh
  import_tasks: install-zsh.yml

- name: Установить менеджер плагинов zi
  import_tasks: install-zi.yml

- name: Установить плагины, указанные в параметре zinit_plugins
  import_tasks: setup-zi-install-plugins.yml

- name: Удалить плагины, не указанные в параметре zinit_plugins
  import_tasks: setup-zi-remove-plugins.yml

- name: Настроить Powerlevel10k
  import_tasks: setup-p10k.yml
  when: "'romkatv/powerlevel10k' in zinit_plugins|map(attribute='name')"
