---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_user_dir is not defined

- name: Установить zsh
  ansible.builtin.import_tasks: install_zsh.yml

- name: Создать каталог $ZSHRC_DIR для zsh-скриптов инициализации
  ansible.builtin.file:
    path: '{{ ansible_env.ZSHRC_DIR }}'
    state: directory
    mode: 0750

- name: Установить менеджер плагинов
  ansible.builtin.import_tasks: install_pm.yml

- name: Настроить промпт, указанные в параметре prompt
  ansible.builtin.import_tasks: setup_prompt.yml

- name: Настроить плагины, указанные в параметре plugins
  ansible.builtin.import_tasks: setup_pm.yml
