---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_user_dir is not defined

- name: Установить zsh
  ansible.builtin.import_tasks: install_zsh.yml

- name: Установить менеджер плагинов
  ansible.builtin.import_tasks: install_pm.yml

- name: Создать каталог $ZSHRC_DIR для zsh-скриптов инициализации
  ansible.builtin.file:
    path: '{{ ansible_env.ZSHRC_DIR }}'
    state: directory
    mode: 0750

- name: Сформировать список устанавливаемых плагинов без промпт-плагинов
  ansible.builtin.set_fact:
    _plugins: '{{ _plugins | rejectattr("name", "eq", item.value) }}'
  vars:
    _plugins: '{{ plugins }}'
  loop: '{{ _prompts | dict2items }}'

- name: Проверить на корректное значение параметра prompt='{{ prompt }}'
  ansible.builtin.assert:
    that:
      - prompt in _prompts.keys()

- name: Добавить в начало списка устанавливаемых плагинов указанный промпт-плагин
  ansible.builtin.set_fact:
    _plugins: '{{ [{"name": _prompts[prompt]}] + _plugins }}'
  when: prompt != 'default'

- name: Настроить плагины, указанные в переменной _plugins
  ansible.builtin.import_tasks: setup_pm.yml

- name: Настроить промпт, указанный в параметре prompt
  ansible.builtin.import_tasks: setup_prompt.yml
