---
- name: Установить zsh
  import_tasks: install-zsh.yml

- name: Установить zinit
  import_tasks: install-zinit.yml

- name: Установить zinit-плагины, указанные в параметре zinit_plugins
  import_tasks: setup-zinit-install-plugins.yml

- name: Удалить zinit-плагины, не указанные в параметре zinit_plugins
  import_tasks: setup-zinit-remove-plugins.yml

- name: Настроить Powerlevel10k
  import_tasks: setup-p10k.yml
  when: "'romkatv/powerlevel10k' in zinit_plugins|map(attribute='name')"
