---
- name: Установить zsh
  import_tasks: install_zsh.yml

- name: Установить менеджер плагинов zi
  import_tasks: install_zi.yml

- name: Установить плагины, указанные в параметре plugins
  import_tasks: setup_zi_install_plugins.yml

- name: Удалить плагины, не указанные в параметре plugins
  import_tasks: setup_zi_remove_plugins.yml

- name: Настроить Powerlevel10k
  import_tasks: setup_p10k.yml
  when: "'romkatv/powerlevel10k' in plugins | map(attribute='name')"
