# https://github.com/sindresorhus/pure
---

- name: Установить промпт Pure (pure)
  when: prompt == 'pure'
  block:

    - name: Настроить промпт Pure
      ansible.builtin.debug:
        msg: Использовать настройки по-умолчанию

- name: Удалить промпт Pure (pure)
  when: prompt != 'pure'
  block:

    - name: Удалить конфигурационные файлы промпта Pure (pure)
      ansible.builtin.debug:
        msg: Ничего удалять не нужно
