---
- name: Получить список плагинов, указанных в конфигурации
  set_fact:
    config_plugin_list: "{{ zinit_plugins|map(attribute='name')|map('replace', '/', '---')|list }}"

- name: Получить список установленных плагинов
  find:
    paths: "{{ zinit_home_dir }}/plugins"
    file_type: directory
    recurse: no
  register: r_installed_plugins

- name: Получить нормализованный список установленных плагинов
  set_fact:
    installed_plugin_list: "{{ r_installed_plugins.files|map(attribute='path')|map('basename')|select('match', '^(?!_local).*$')|list }}"

- name: Получить список плагинов для удаления
  set_fact:
    remove_plugin_list: "{{ installed_plugin_list|difference(config_plugin_list) }}"

- name: Удалить плагины, не представленные в конфигурации
  file:
    path: "{{ zinit_home_dir }}/plugins/{{ item }}"
    state: absent
  loop: "{{ remove_plugin_list }}"
  when: remove_plugin_list|length > 0
