---
# https://github.com/romkatv/powerlevel10k

- name: Скопировать файл настроек Powerlevel10k
  copy:
    src: files/.p10k.zsh
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0644"

- name: Включить режим "Instant Prompt"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "\n# {mark} ANSIBLE MANAGED BLOCK - Powerlevel10k (Instant Prompt mode)"
    insertafter: "#!/usr/bin/env zsh"
    block: |

      # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
      # Initialization code that may require console input (password prompts, [y/n]
      # confirmations, etc.) must go above this block; everything else may go below.
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi

- name: Включить загрузку файла настроек Powerlevel10k
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "\n# {mark} ANSIBLE MANAGED BLOCK - Powerlevel10k (configuration)"
    insertafter: EOF
    block: |

      # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
