# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
---
MD013: false
MD024:
  allow_different_nesting: true
MD033:
  allowed_elements:
    - br
    - table
    - tbody
    - td
    - th
    - thead
    - tr
