---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий компании
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакеты приложений
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ packages }}'
  become: true

# Стандартная команда vagrant autocomplete install довольно топорно прописывает
# вызов autocompletion-скрипта в конец скриптов ~/.bashrc и ~/.zshrc

- name: Установить shell autocompletion для Vagrant
  vars:
    _bash_completion_dir: /etc/bash_completion.d
    _zsh_completion_dir: /usr/share/zsh/vendor-completions
  when: "'vagrant' in packages"
  tags:
    - autocompletion
  block:
    - name: Получить версию Vagrant
      ansible.builtin.shell:
        cmd: vagrant --version | cut -d' ' -f2
      register: r__vagrant_version
      changed_when: false

    - name: 'Версия Vagrant: {{ r__vagrant_version.stdout }}'
      ansible.builtin.set_fact:
        _vagrant_version: '{{ r__vagrant_version.stdout }}'

    - name: Вычислить пути до autocompletion-скриптов
      ansible.builtin.set_fact:
        _vagrant_completion_script_bash: /opt/vagrant/embedded/gems/gems/vagrant-{{ _vagrant_version }}/contrib/bash/completion.sh
        _vagrant_completion_script_zsh: /opt/vagrant/embedded/gems/gems/vagrant-{{ _vagrant_version }}/contrib/zsh/_vagrant

    - name: Прописать autocompletion-скрипт в системе для bash ({{ _bash_completion_dir }}/)
      ansible.builtin.copy:
        content: |
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
          # #  Managed by Ansible                                                     # #
          # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
          [[ -e {{ _vagrant_completion_script_bash }} ]] && . {{ _vagrant_completion_script_bash }}
        dest: '{{ _bash_completion_dir }}/vagrant'
        mode: 0644
      become: true
      tags:
        - bash

    - name: Прописать autocompletion-скрипт в системе для zsh ({{ _zsh_completion_dir }}/)
      ansible.builtin.copy:
        src: '{{ _vagrant_completion_script_zsh }}'
        dest: '{{ _zsh_completion_dir }}'
        mode: 0644
      become: true
      tags:
        - zsh
