---
galaxy_info:
  author: Radimir Mikhailov
  description: Install Visual Studio Code
  license: MIT
  role_name: vscode

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs: {}
