---
- name: Установить python-модуль psutil для работы ansible-модуля dconf
  pip:
    name: psutil

- name: Настроить клавиатуру
  import_tasks: setup-keyboard.yml

- name: Настроить общие параметры GNOME Shell
  import_tasks: setup-general.yml

- name: Установить расширения GNOME Shell
  import_tasks: install-extensions.yml
