---
- name: Установить pip3 и сопутствующие модули
  become: yes
  apt:
    name:
      - python3-venv
      - python3-dev
      - python3-pip
    state: present

- name: Установить python-модули для работы ansible-модуля dconf
  pip:
    name: psutil

- name: Настроить клавиатуру
  import_tasks: setup-keyboard.yml

- name: Установить расширения GNOME Shell
  import_tasks: install-extensions.yml
