---
- name: Установить python-модуль psutil для работы ansible-модуля community.general.dconf
  ansible.builtin.apt:
    name: python3-psutil
    state: present
  become: true

- name: Настроить клавиатуру
  import_tasks: setup-keyboard.yml

- name: Настроить общие параметры GNOME Shell
  import_tasks: setup-general.yml

- name: Установить расширения GNOME Shell
  import_tasks: install-extensions.yml

# - name: Установить тему GNOME Shell
#   import_tasks: install-theme.yml
