---
- name: Установить python-модули для работы ansible-модуля dconf
  pip:
    name: psutil

- name: Настроить клавиатуру
  import_tasks: setup-keyboard.yml

- name: Установить расширения GNOME Shell
  import_tasks: install-extensions.yml
