# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

export PATH="$PATH:$HOME/.local/bin"

# Так как переменная EDITOR может переопределяться, например, в VS Code
[ -z "$EDITOR" ] && export EDITOR=vim
