---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_distribution is not defined

- name: Установить Snap-пакет приложения
  community.general.snap:
    name: telegram-desktop
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Для Fedora
  become: true
  block:

  - name: Включить Flatpak-репозиторий Flathub
    community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present

  - name: Установить Flatpak-пакет приложения
    community.general.flatpak:
      name: org.telegram.desktop
      remote: flathub
      state: present

  when: ansible_distribution == 'Fedora'
