---
galaxy_info:
  author: Radimir Mikhailov
  description: Install Yandex Disk Indicator
  license: MIT
  role_name: yandex_disk_indicator

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs: {}
