---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий приложения
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакет приложения
  ansible.builtin.package:
    name: yandex-disk
    state: present
  become: true

  # При установке RPM-пакета запускается scriptlet пакета, который всегда прописывает
  # в repo-файл секцию [yandex], даже если она уже существует. Эта секция абсолютно
  # идентична секции, устанавливаемой в add_repo_os_family_redhat.yml
- name: '{{ ansible_os_family }}: удалить дублирующую секцию из repo-файла'
  community.general.ini_file:
    path: /etc/yum.repos.d/yandex-disk.repo
    mode: 0644
    section: yandex
    state: absent
  become: true
  when: ansible_os_family == 'RedHat'

- name: 'Создать каталог для файлов облака: {{ dir }}'
  ansible.builtin.file:
    path: '{{ dir }}'
    state: directory
    mode: 0700

- name: Создать каталог для конфигурационных файлов приложения
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ _config_subdir }}'
    state: directory
    mode: 0700

- name: Настроить конфигурационный файл приложения
  ansible.builtin.template:
    src: config.cfg
    dest: '{{ ansible_user_dir }}/{{ _config_subdir }}/{{ _config_filename }}'
    mode: 0640

- name: Настроить systemd unit-файл, общий для всех пользователей
  ansible.builtin.template:
    src: yandex-disk@.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  become: true

- name: 'Включить автозагрузку yandex-disk. Не забудьте привязать это устройство командой: $ yandex-disk token'
  ansible.builtin.systemd:
    name: yandex-disk@{{ ansible_user_id }}.service
    enabled: true
  become: true
