---
- name: Установить apt-пакет приложения и рекомендуемые зависимости
  ansible.builtin.apt:
    name:
      - ranger
      - file
      - python3-chardet
    state: latest
    update_cache: yes
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
  become: true

- name: Скопировать конфигурационный файл приложения
  ansible.builtin.copy:
    src: files/rc.conf
    dest: '{{ ansible_user_dir }}/.config/ranger/'
    mode: 0644
