---
- name: Установить пакет приложения и рекомендуемые зависимости
  ansible.builtin.package:
    name:
      - ranger
      - file  # for determining file types
      - python3-chardet  # for improved encoding detection of text files
    state: present
  become: true

- name: Скопировать конфигурационный файл приложения
  ansible.builtin.copy:
    src: files/rc.conf
    dest: '{{ ansible_user_dir }}/.config/ranger/'
    mode: 0644
