---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Установить приложение для семейства ОС {{ ansible_os_family }}
  ansible.builtin.include_tasks: os_family_{{ ansible_os_family | lower }}.yml

# Чтобы в ВМ, запущенных пользователем ansible_user_id, были доступны USB-устройства
- name: Добавить пользователя '{{ ansible_user_id }}' в группу 'vboxusers'
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: vboxusers
    append: true
  become: true
