---
- name: "Создать каталог для иконки приложения: {{ icons_dir }}"
  become: yes
  file:
    path: "{{ icons_dir }}"
    state: directory

- name: Обновить иконку приложения
  become: yes
  get_url:
    url: "{{ app_icon_url }}"
    dest: "{{ icons_dir }}/{{ app_name }}.png"
    # Скачать, но обновить, только если содержимое файла изменилось
    force: yes
