---
- name: Установить Snap-пакет приложения
  become: yes
  snap:
    name: flameshot
    state: present

- name: Запустить приложение, чтобы оно создало свои каталоги и файлы
  shell: flameshot --version
  changed_when: no

- name: Настроить приложение
  ini_file:
    path: '{{ ansible_user_dir }}/snap/flameshot/current/.config/flameshot/flameshot.ini'
    no_extra_spaces: yes
    section: General
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "showHelp", value: "false" }
    - { option: "uiColor", value: "#90c9e5" }

- name: Настроить автозапуск приложения
  copy:
    content: |
      [Desktop Entry]
      Name=flameshot
      Icon=flameshot
      Exec=flameshot
      Terminal=false
      Type=Application
      X-GNOME-Autostart-enabled=true
    dest: "{{ ansible_user_dir }}/.config/autostart/Flameshot.desktop"
