---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_user_dir is not defined

- name: Установить пакет приложения
  ansible.builtin.package:
    name: flameshot
    state: present
  become: true

- name: Установить пакеты, необходимые для работы Flameshot в среде GNOME Wayland
  ansible.builtin.package:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
    state: present
  become: true

- name: Создать каталог для конфигурационного файла приложения
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/flameshot'
    state: directory
    mode: 0755

- name: Настроить приложение
  community.general.ini_file:
    path: '{{ ansible_user_dir }}/.config/flameshot/flameshot.ini'
    create: true
    mode: 0644
    no_extra_spaces: true
    section: General
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ options | dict2items }}'
