---
- name: Установить Snap-пакет приложения
  community.general.snap:
    name: flameshot
    state: present
  become: true

- name: Установить пакеты, необходимые для работы Flameshot в среде GNOME Wayland
  ansible.builtin.package:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
    state: present
  become: true

- name: Запустить приложение, чтобы оно создало свои каталоги и файлы
  ansible.builtin.command: flameshot --version
  changed_when: false

- name: Настроить приложение
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/flameshot/current/.config/flameshot/flameshot.ini'
    no_extra_spaces: true
    section: General
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ options | dict2items }}'

- name: Создать служебный каталог для ярлыков запускаемых автоматически приложений
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/autostart'
    state: directory

- name: Настроить автозапуск приложения
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=flameshot
      Icon=flameshot
      Exec=flameshot
      Terminal=false
      Type=Application
      X-GNOME-Autostart-enabled=true
    dest: '{{ ansible_user_dir }}/.config/autostart/Flameshot.desktop'
