---
- name: Добавить официальный PPA приложения
  become: yes
  apt_repository:
    repo: 'ppa:remmina-ppa-team/remmina-next'
    state: present

- name: Установить последнюю версию приложения
  become: yes
  apt:
    name: remmina
    state: latest
    update_cache: yes

- name: Убрать плагин сохранения паролей в Gnome Keyring
  become: yes
  apt:
    name: remmina-plugin-secret
    state: absent
