---
- name: Установить Snap-пакет приложения
  become: yes
  snap:
    name: remmina
    state: present
    classic: yes

# - name: Убрать плагин сохранения паролей в Gnome Keyring
#   become: yes
#   apt:
#     name: remmina-plugin-secret
#     state: absent
