---
- name: Установить Snap-пакет приложения
  community.general.snap:
    name: remmina
    state: present
  become: true

- name: Запустить приложение, чтобы оно создало свои каталоги и файлы
  ansible.builtin.command: remmina --version
  changed_when: false

- name: Создать каталог для хранения файлов-профилей соединений Remmina
  ansible.builtin.file:
    path: '{{ _connections_dir }}'
    state: directory

- name: Установить secret приложения
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/remmina/current/.config/remmina/remmina.pref'
    no_extra_spaces: true
    section: remmina_pref
    option: secret
    value: '{{ remmina_secret }}'
  when: remmina_secret is defined

- name: Настроить приложение
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/remmina/current/.config/remmina/remmina.pref'
    no_extra_spaces: true
    section: remmina_pref
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
    - { option: datadir_path, value: '{{ _connections_dir }}' }
    - { option: disable_tray_icon, value: 'true' }
    - { option: prevent_snap_welcome_message, value: 'true' }
    - { option: view_file_mode, value: '1' }
