---
- name: Установить Snap-пакет приложения
  community.general.snap:
    name: remmina
    state: present
  become: true

- name: Запустить приложение, чтобы оно создало свои каталоги и файлы
  ansible.builtin.command: remmina --version
  changed_when: false

- name: Создать каталог для хранения файлов-профилей соединений Remmina
  ansible.builtin.file:
    path: '{{ _connections_dir }}'
    state: directory

- name: Установить в параметрах приложения каталог для профилей соединений в '{{ _connections_dir }}'
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/remmina/current/.config/remmina/remmina.pref'
    no_extra_spaces: true
    section: remmina_pref
    option: datadir_path
    value: '{{ _connections_dir }}'

- name: Установить в параметрах приложения secret приложения
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/remmina/current/.config/remmina/remmina.pref'
    no_extra_spaces: true
    section: remmina_pref
    option: secret
    value: '{{ secret }}'
  when: secret is defined

- name: Установить параметры приложения
  ansible.builtin.ini_file:
    path: '{{ ansible_user_dir }}/snap/remmina/current/.config/remmina/remmina.pref'
    no_extra_spaces: true
    section: remmina_pref
    option: '{{ item.key }}'
    value: '{{ item.value | string }}'
  loop: '{{ options | dict2items }}'
