# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

export PATH="$PATH:$HOME/.krew/bin"

# FIXME: в zsh получаем ошибку "zsh: compdef: command not found..."
# source <(kubectl completion zsh)
