# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

alias k='kubectl'

# FIXME: в zsh получаем ошибку "zsh: compdef: command not found..."
# source <(kubectl completion zsh)
