---
- name: Установить пакет xbindkeys
  become: yes
  apt:
    name: xbindkeys
    state: latest

- name: Определить команды переключения раскладок для Gnome
  include_vars:
    file: vars/switch-commands-gnome.yaml
    name: switch_commands
  when: ansible_env.XDG_CURRENT_DESKTOP in ("Unity", "ubuntu:GNOME")

- name: Настроить конфигурационный файл xbindkeysrc
  template:
    src: .xbindkeysrc.j2
    dest: "{{ ansible_env.HOME }}/.xbindkeysrc"
  notify: reload-xbindkeys-config

- name: Сделать автоматическим запуск xbindkeys
  copy:
    src: files/.xprofile
    dest: "{{ ansible_env.HOME }}/"
    mode: "755"
