---
- name: Установить необходимые пакеты
  become: yes
  apt:
    name:
      - libyaml-cpp-dev
    state: present

- name: Установить исполняемые файлы interception
  become: yes
  copy:
    src: files/bin/
    dest: /usr/local/bin
    mode: "755"

- name: Скопировать конфигурационные файлы interception
  become: yes
  copy:
    src: files/etc/
    dest: "{{ config_dir }}"
  notify: restart-udevmon

- name: Настроить конфигурационный файл демона udevmon
  become: yes
  template:
    src: templates/udevmon.yaml.j2
    dest: "{{ config_dir }}/udevmon.yaml"
  notify: restart-udevmon

- name: Настроить systemd unit-файл демона udevmon
  become: yes
  template:
    src: templates/udevmon.service.j2
    dest: /etc/systemd/system/udevmon.service

- name: Настроить запуск демона udevmon через systemd
  become: yes
  systemd:
    service: udevmon
    enabled: yes
    state: started
