---
- name: Установить пакет xbindkeys
  become: yes
  apt:
    name: xbindkeys
    state: latest

- name: Определить команды переключения раскладок для Gnome
  include_vars:
    file: vars/switch-commands-gnome.yaml
    name: switch_commands
  when: ansible_env.XDG_CURRENT_DESKTOP in ("Unity", "ubuntu:GNOME")

- name: Настроить конфигурационный файл xbindkeysrc
  template:
    src: .xbindkeysrc.j2
    dest: "{{ ansible_user_dir }}/.xbindkeysrc"
  notify: reload-xbindkeys-config

- name: Настроить скрипт on-locking-desktop.sh
  become: yes
  template:
    src: on-locking-desktop.sh
    dest: /usr/local/bin
    mode: "755"

- name: Сделать автоматическим запуск xbindkeys и on-locking-desktop.sh
  copy:
    src: files/.xprofile
    dest: "{{ ansible_user_dir }}/"
    mode: "755"
