---
- name: Установить python-модуль psutil для работы ansible-модуля community.general.dconf
  ansible.builtin.package:
    name: python3-psutil
    state: present
  become: true

- name: Назначить кастомные клавиатурные привязки
  ansible.builtin.include_tasks: add_custom_keybinding.yml
  loop: '{{ keybindings }}'
  loop_control:
    index_var: custom_index

  # Включаются только перечисленные в keybindings привязки
- name: Включить назначенные кастомные клавиатурные привязки
  community.general.dconf:
    key: '{{ _dconf_key }}'
    value: "{{ range(keybindings | length) | map('regex_replace', '^(.*)$', _dconf_key+'/custom\\1/') | to_json }}"

