---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий Kubernetes
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакет kubectl
  ansible.builtin.package:
    name: kubectl
    state: present
  become: true

- name: Создать каталог $ZSHRC_DIR для zsh-скриптов инициализации
  ansible.builtin.file:
    path: '{{ ansible_env.ZSHRC_DIR }}'
    state: directory
    mode: 0750

- name: Настроить zsh
  ansible.builtin.copy:
    src: 40-kubectl.zsh
    dest: '{{ ansible_env.ZSHRC_DIR }}'
    mode: 0644

- name: Установить менеджер плагинов krew
  ansible.builtin.import_tasks: install_krew.yml
