---
- name: Установить минимальный набор пакетов
  become: yes
  apt:
    name:
      - curl
      - git
      - inetutils-traceroute
      - neovim
      - xsel
    state: latest
    update_cache: yes
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
