---
galaxy_info:
  author: Radimir Mikhailov
  description: Install Flameshot
  license: MIT

  min_ansible_version: '2.7'

  platforms:
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs:
  main:
    options:
      options:
        description: Словарь устанавливаемых параметров Flameshot в секции `[General]`
        required: false
        type: dict
