---
galaxy_info:
  author: Radimir Mikhailov
  description: Install zsh with plugins
  license: MIT

  min_ansible_version: '2.7'

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs:
  main:
    options:
      aliases:
        description: Словарь алиасов
        required: false
        type: dict
      plugins:
        description: Список zsh-плагинов
        required: false
        type: list
        elements: dict
        options:
          name:
            description: имя плагина в виде <repo>/<plugin>
            required: true
            type: str
          path:
            description: подкаталог или файл внутри репозитория плагина
            required: false
            type: path
      zsh_home_subdir:
        description: Подкаталог в домашнем каталоге пользователя для размещения конфигурационных файлов zsh
        required: false
        type: path
