---
# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: Установить пакеты, необходимые для сборки произвольных версий Python
  become: true
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - make
      - llvm
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов

- name: Склонировать/обновить pyenv  # noqa: latest (предотвратить срабатывание правила latest[git] Ansible-линтера)
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ pyenv_home_dir }}'
    force: true
    update: true

- name: Создать каталог $ZSHRC_DIR для zsh-скриптов инициализации
  ansible.builtin.file:
    path: '{{ ansible_env.ZSHRC_DIR }}'
    state: directory
    mode: 0750

- name: Сгенерировать {{ pyenv_init_script }}
  ansible.builtin.template:
    src: '{{ pyenv_init_script }}.j2'
    dest: '{{ ansible_env.ZSHRC_DIR }}/{{ pyenv_init_script }}'
    mode: 0644
