---
- name: Установить/обновить pip
  become: true
  apt:
    name: python3-pip
    state: latest
    update_cache: true
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов

- name: Установить приложение pipenv
  become: yes
  apt:
    name: pipenv
    state: present

- name: Установить приложение pyenv
  import_tasks: install-pyenv.yml
