---
- name: Fedora | Ускорить работу dnf
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    no_extra_spaces: true
    section: main
    option: '{{ kv.key }}'
    value: '{{ kv.value }}'
    mode: '0644'
  become: true
  loop: '{{ _options | dict2items }}'
  loop_control:
    loop_var: kv
  vars:
    _options:
      fastestmirror: 'True'
      max_parallel_downloads: 10

# https://rpmfusion.org/Configuration
- name: Fedora | Включить репозитории RPM Fusion (free и nonfree)
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    # Необходимо отключить проверку подписей rpm-пакетов RPM Fusion, так как на момент
    # установки этих пакетов в системе еще не установлены соответствующие ключи. Эти ключи
    # как раз и устанавливаются этими пакетами
    disable_gpg_check: true
  become: true

# Включить полноценный репозиторий Flathub.org.
#
# В систему всегда устанавливается пакет fedora-flathub-remote, который добавляет в систему Flatpak-репозиторий
# flathub с включенной фильтрацией пакетов от Fedora - можно устанавливать приложения с Flathub.org только из
# белого списка.
# Даже если удалить этот пакет или не включать/отключить опцию Fedora Third Party Repositories в мастере
# первоначальной настройки системы или в приложении Software, этот Flatpak-репозиторий всё равно остаётся
# в системе в статусе disabled:
#
#   flatpak remotes --system --show-disabled
#
# И это мешает установить нормальный flathub. Исправляем это.

- name: Включить полноценный репозиторий Flathub.org
  block:

    - name: Fedora | Проверить, установлен ли фильтрующий Flatpak-репозиторий Flathub
      ansible.builtin.shell:
        cmd: flatpak remotes --system --show-disabled | grep -E '^flathub\s.*filtered.*' | wc -l
      register: r__filtered_flathub_count
      changed_when: false

    - name: Fedora | Удалить ФИЛЬТРУЮЩИЙ Flatpak-репозиторий Flathub от Fedora
      ansible.builtin.command:
        cmd: flatpak remote-delete --system flathub
      become: true
      changed_when: false
      when: r__filtered_flathub_count.stdout | int > 0

    - name: Fedora | Включить стандартный Flatpak-репозиторий Flathub БЕЗ ФИЛЬТРА
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present
      become: true
