---
- name: Fedora | Ускорить работу dnf
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    no_extra_spaces: true
    section: main
    option: '{{ kv.key }}'
    value: '{{ kv.value }}'
    mode: '0644'
  become: true
  loop: '{{ _options | dict2items }}'
  loop_control:
    loop_var: kv
  vars:
    _options:
      fastestmirror: 'True'
      max_parallel_downloads: 10

# https://rpmfusion.org/Configuration

- name: Fedora | Включить репозитории RPM Fusion (free и nonfree)
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    # Необходимо отключить проверку подписей rpm-пакетов RPM Fusion, так как на момент
    # установки этих пакетов в системе еще не установлены соответствующие ключи. Эти ключи
    # как раз и устанавливаются этими пакетами
    disable_gpg_check: true
  become: true

# Включить полноценный репозиторий Flathub.org.
#
# В систему всегда устанавливается пакет fedora-flathub-remote, который добавляет в систему Flatpak-репозиторий
# flathub с включенной фильтрацией пакетов от Fedora - можно устанавливать приложения с Flathub.org только из
# белого списка.
# Даже если удалить этот пакет или не включать/отключить опцию Fedora Third Party Repositories в мастере
# первоначальной настройки системы или в приложении Software, этот Flatpak-репозиторий всё равно остаётся
# в системе в статусе disabled:
#
#   flatpak remotes --system --show-disabled
#
# И это мешает установить нормальный flathub. Исправляем это.

- name: Включить полноценный репозиторий Flathub.org
  block:

    - name: Fedora | Проверить, установлен ли фильтрующий Flatpak-репозиторий Flathub
      ansible.builtin.shell:
        cmd: flatpak remotes --system --show-disabled | grep -E '^flathub\s.*filtered.*' | wc -l
      register: r__filtered_flathub_count
      changed_when: false

    - name: Fedora | Удалить ФИЛЬТРУЮЩИЙ Flatpak-репозиторий Flathub от Fedora
      ansible.builtin.command:
        cmd: flatpak remote-delete --system flathub
      become: true
      changed_when: false
      when: r__filtered_flathub_count.stdout | int > 0

    - name: Fedora | Включить стандартный Flatpak-репозиторий Flathub БЕЗ ФИЛЬТРА
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present
      become: true

# https://rpmfusion.org/Howto/Multimedia

- name: Переключиться на полную версию фреймворка FFmpeg (https://ffmpeg.org)
  block:

    - name: Fedora | Удалить урезанную версию фреймворка FFmpeg
      ansible.builtin.dnf:
        name: ffmpeg-free
        state: absent
      become: true

    - name: Fedora | Установить полную версию фреймворка FFmpeg
      ansible.builtin.dnf:
        name: ffmpeg
        state: present
        allowerasing: true
      become: true

- name: Установить дополнительные кодеки
  block:

    - name: Fedora | Включить поддержку фреймворка GStreamer с дополнительными кодеками
      ansible.builtin.dnf:
        name: '@Multimedia'  # Посмотреть содержимое группы: dnf group info Multimedia
        state: present
        exclude:
          - PackageKit-gstreamer-plugin
        install_weak_deps: false
      become: true

    - name: Fedora | Добавить в GStreamer поддержку кодека H.264
      ansible.builtin.dnf:
        name: gstreamer1-plugin-openh264
        state: present
      become: true

- name: Включить аппаратное ускорение видео
  block:

    - name: Fedora | Получить информацию об используемых видеокартах
      ansible.builtin.shell:
        cmd: lspci | grep VGA
      register: r__vga_controllers
      changed_when: false

    - name: Fedora | Установить драйверы для Intel Graphics
      ansible.builtin.dnf:
        name: intel-media-driver
        state: present
      become: true
      when: r__vga_controllers.stdout.find('Intel') != -1

- name: Добавить поддержку кодеков H.264/265 для Mesa-based VA-API video acceleration drivers (https://www.mesa3d.org)
  block:

    - name: Fedora | Удалить Mesa-based VA-API видеодрайвер без поддержки H.264/265
      ansible.builtin.dnf:
        name: mesa-va-drivers
        state: absent
      become: true

    - name: Fedora | Установить Mesa-based VA-API видеодрайвер с поддержкой H.264/265
      ansible.builtin.dnf:
        name: mesa-va-drivers-freeworld
        state: present
      become: true

- name: Добавить поддержку кодеков H.264/265 для Mesa-based VDPAU drivers (https://www.mesa3d.org)
  block:

    - name: Fedora | Удалить Mesa-based драйвер VDPAU без поддержки H.264/265
      ansible.builtin.dnf:
        name: mesa-vdpau-drivers
        state: absent
      become: true

    - name: Fedora | Установить Mesa-based драйвер VDPAU с поддержкой H.264/265
      ansible.builtin.dnf:
        name: mesa-vdpau-drivers-freeworld
        state: present
      become: true
