---
# https://rpmfusion.org/Configuration
- name: '{{ ansible_distribution }}: включить репозитории RPM Fusion (free и nonfree)'
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    # Необходимо отключить проверку подписей rpm-пакетов RPM Fusion, так как на момент
    # установки этих пакетов в системе еще не установлены соответствующие ключи. Эти ключи
    # как раз и устанавливаются этими пакетами
    disable_gpg_check: true
  become: true
