---
- name: '{{ ansible_distribution }}: ускорить работу dnf'
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    no_extra_spaces: true
    section: main
    option: '{{ kv.key }}'
    value: '{{ kv.value }}'
  become: true
  loop: '{{ _options | dict2items }}'
  loop_control:
    loop_var: kv
  vars:
    _options:
      fastestmirror: 'True'
      max_parallel_downloads: 5

# https://rpmfusion.org/Configuration
- name: '{{ ansible_distribution }}: включить репозитории RPM Fusion (free и nonfree)'
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    # Необходимо отключить проверку подписей rpm-пакетов RPM Fusion, так как на момент
    # установки этих пакетов в системе еще не установлены соответствующие ключи. Эти ключи
    # как раз и устанавливаются этими пакетами
    disable_gpg_check: true
  become: true

- name: '{{ ansible_distribution }}: включить Flatpak-репозиторий Flathub'
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
  become: true
