---
- name: '{{ ansible_distribution }}: ускорить работу dnf'
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    no_extra_spaces: true
    section: main
    option: '{{ kv.key }}'
    value: '{{ kv.value }}'
  become: true
  loop: '{{ _options | dict2items }}'
  loop_control:
    loop_var: kv
  vars:
    _options:
      fastestmirror: 'True'
      max_parallel_downloads: 5

# https://rpmfusion.org/Configuration
- name: '{{ ansible_distribution }}: включить репозитории RPM Fusion (free и nonfree)'
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    # Необходимо отключить проверку подписей rpm-пакетов RPM Fusion, так как на момент
    # установки этих пакетов в системе еще не установлены соответствующие ключи. Эти ключи
    # как раз и устанавливаются этими пакетами
    disable_gpg_check: true
  become: true

# После включения Fedora Third Party Repositories в приложении Software или при установке системы
# добавляется Flatpak-репозиторий flathub с включенной фильтрацией от Fedora, при которой можно
# устанавливать приложения с Flathub.org только из белого списка (dnf info fedora-flathub-remote).
# Даже при отключении Fedora Third Party Repositories фильтрующий репозиторий flathub всё равно
# присутствует в системе в статусе disabled (flatpak remotes --show-disabled) и это мешает установить
# нормальный flathub. Исправляем это.

- name: '{{ ansible_distribution }}: проверить, установлен ли фильтрующий Flatpak-репозиторий Flathub'
  ansible.builtin.shell:
    cmd: flatpak remotes --system --show-disabled | grep -E '^flathub\s.*filtered.*' | wc -l
  register: r__filtered_flathub_count
  changed_when: false

- name: '{{ ansible_distribution }}: удалить ФИЛЬТРУЮЩИЙ Flatpak-репозиторий Flathub от Fedora'
  ansible.builtin.command:
    cmd: flatpak remote-delete --system flathub
  become: true
  when: r__filtered_flathub_count.stdout | int > 0

- name: '{{ ansible_distribution }}: включить стандартный Flatpak-репозиторий Flathub БЕЗ ФИЛЬТРА'
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
  become: true
