---
_vpn_base_url: http://94.131.15.172:8080/banned-from-russia/hashicorp

_base_url:
  # apt: https://apt.releases.hashicorp.com
  # rpm: https://rpm.releases.hashicorp.com
  apt: '{{ _vpn_base_url }}/apt'
  rpm: '{{ _vpn_base_url }}/rpm'

_apt_urls:
  key: '{{ _base_url.apt }}/gpg'
  repo: '{{ _base_url.apt }}'

_rpm_urls:
  key: '{{ _base_url.rpm }}/gpg'
  repo: '{{ _base_url.rpm }}/fedora/$releasever/$basearch/stable'
  repo_file: '{{ _base_url.rpm }}/fedora/hashicorp.repo'
