---
_apt_urls:
  key: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt/gpg
  repo: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt
  # key: https://apt.releases.hashicorp.com/gpg
  # repo: https://apt.releases.hashicorp.com
