---
- name: '{{ ansible_os_family }}: установить публичный ключ репозитория'
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: '{{ ansible_os_family }}: добавить официальный репозиторий'
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
    enabled: true
    state: present
  become: true

