---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий приложения
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакет приложения
  ansible.builtin.package:
    name: code
    state: present
  become: true

# https://code.visualstudio.com/docs/sourcecontrol/overview#_vs-code-as-git-difftool-and-mergetool
- name: Настроить git на использование VS Code
  community.general.git_config:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    scope: global
  loop:
    - {key: diff.tool, value: default-difftool}
    - {key: difftool.default-difftool.cmd, value: 'code --wait --diff $LOCAL $REMOTE'}
    - {key: merge.tool, value: code}
    - {key: mergetool.code.cmd, value: 'code --wait --merge $REMOTE $LOCAL $BASE $MERGED'}
