---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий приложения
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакет приложения
  ansible.builtin.package:
    name: code
    state: present
  become: true
