---
galaxy_info:
  author: Radimir Mikhailov
  description: Define GNOME custom keybindings
  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

argument_specs:
  main:
    options:
      keybindings:
        description: Список клавиатурных привязок
        required: true
        type: list
        elements: dict
        options:
          name:
            description: Название привязки
            required: true
            type: str
          binding:
            description: Комбинация клавиш
            required: true
            type: str
          command:
            description: shell-команда
            required: true
            type: str
