---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Установить пакет приложения
  ansible.builtin.package:
    name: fzf
    state: present
  become: true

- name: Создать каталог $ZSHRC_DIR для zsh-скриптов инициализации
  ansible.builtin.file:
    path: '{{ ansible_env.ZSHRC_DIR }}'
    state: directory
    mode: 0750

- name: Создать zsh-скрипт инициализации приложения
  ansible.builtin.template:
    src: 40-fzf.zsh
    dest: '{{ ansible_env.ZSHRC_DIR }}'
    mode: 0644
  vars:
    _script_key_binding: '{{ _shell_scripts_dir[ansible_os_family | lower] }}/key-bindings.zsh'
