---
- name: Установить последнюю версию Vim
  ansible.builtin.apt:
    name: vim
    state: latest
    update_cache: true
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
  become: true

- name: Скопировать файл настроек Vim
  ansible.builtin.copy:
    src: files/.vimrc
    dest: '{{ ansible_user_dir }}/'

- name: Получить путь к текущему редактору по-умолчанию
  ansible.builtin.shell: update-alternatives --query editor | grep "Value" | cut -d" " -f2
  register: r__default_editor
  changed_when: false

- name: 'Путь к редактору по-умолчанию: {{ r__default_editor.stdout }}'
  ansible.builtin.set_fact:
    default_editor: '{{ r__default_editor.stdout }}'

- name: Установить Vim редактором по-умолчанию
  ansible.builtin.command: update-alternatives --set editor /usr/bin/vim.basic
  become: true
  changed_when: true
  when: default_editor != '/usr/bin/vim.basic'
