---
- name: Установить последнюю версию VIM
  become: yes
  apt:
    name: vim
    state: latest
    update_cache: yes
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов

- name: Скопировать файл настроек VIM
  copy:
    src: files/.vimrc
    dest: "{{ ansible_user_dir }}/"

- name: Скопировать файл .editorconfig
  copy:
    src: files/.editorconfig
    dest: "{{ ansible_user_dir }}/"

- name: Получить путь к текущему редактору по-умолчанию
  shell: update-alternatives --query editor | grep "Value" | cut -d" " -f2
  register: r__default_editor
  changed_when: no

- name: "Путь к редактору по-умолчанию: {{ r__default_editor.stdout }}"
  set_fact:
    default_editor: "{{ r__default_editor.stdout }}"

- name: Установить VIM редактором по-умолчанию
  become: yes
  shell: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: yes
  when: default_editor != "/usr/bin/vim.basic"
