---
- name: Установить pip3 и сопутствующие модули
  become: true
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
    state: present
    update_cache: true
    cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов

- name: Установить через pip3 приложение pipx
  ansible.builtin.pip:
    name: pipx
    executable: pip3
    extra_args: --user

- name: Настроить автодополнение
  ansible.builtin.copy:
    src: files/.zshrc-pipx.zsh
    dest: '{{ ansible_env.HOME }}'
    mode: 0644
