---
- name: Установить pip3 и сопутствующие модули
  become: yes
  apt:
    name:
      - python3-venv
      - python3-dev
      - python3-pip
    state: present

- name: Установить через pip3 приложение pipx
  pip:
    name: pipx
    executable: pip3
    extra_args: --user

- name: Настроить автодополнение
  copy:
    src: files/.zshrc-pipx.zsh
    dest: "{{ ansible_env.HOME }}"
