---
- name: Добавить официальный репозиторий Docker
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить Docker и Docker Compose plugin
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: true

- name: Добавить пользователя '{{ ansible_user_id }}' в группу 'docker'
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
  become: true

- name: Создать каталог /etc/docker
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true
  tags:
    - configure

- name: Создать/обновить конфигурационный файл демона docker
  ansible.builtin.copy:
    content: >
      {{ _daemon_json_default | combine(daemon_json_extra, recursive=True) | to_nice_json }}
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  become: true
  notify: restart-docker
  tags:
    - configure

- name: Обеспечить запуск Docker после перезагрузки системы
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true
