---
- name: Добавить официальный репозиторий Docker
  ansible.builtin.include_tasks: add-repo-os-family-{{ ansible_os_family | lower }}.yml

- name: Установить Docker и Docker Compose plugin
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: true

- name: Добавить пользователя '{{ ansible_user_id }}' в группу 'docker'
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
  become: true

- name: Обеспечить запуск Docker после перезагрузки системы
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true
