---
- name: Настройка Linux-окружения
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: [min]

  vars:
    # Подкаталог в домашнем каталоге пользователя для всех конфигурационных файлов оболочки zsh
    ZSH_HOME_SUBDIR: .config/zsh

    prompt: p10k
    _prompts:
      default: ''
      p10k: romkatv/powerlevel10k
      pure: belak/zsh-utils
    plugins:
      - name: zdharma/fast-syntax-highlighting
      - name: romkatv/powerlevel10k
      - name: zsh-users/zsh-autosuggestions
      - name: zsh-users/zsh-completions
      - name: belak/zsh-utils
        path: completion
      - name: Aloxaf/fzf-tab  # всегда должен быть последним в списке плагинов

  environment:
    # Переменная окружения ZSHRC_DIR используется в ролях, устанавливающих свои zsh-скрипты
    # инициализации. Её значение устанавливается в роли zsh, но при первом запуске плейбука
    # эта переменная еще недоступна. Поэтому устанавливается здесь вручную.
    ZSHRC_DIR: ~/{{ ZSH_HOME_SUBDIR }}/zshrc.d

  pre_tasks:

    - name: Установить часовой пояс
      community.general.timezone:
        name: Asia/Novokuznetsk
      become: true
      tags:
        - timezone

    - name: Создать мои каталоги
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/{{ item }}'
        state: directory
        mode: 0700
      loop:
        - .local/bin
        - 1clouds  # синхронизируемые с облаками файлы
        - 1git     # все git-репозитории, кроме dotfiles
        - 1temp    # временные файлы, которые "не жалко"
      tags:
        - dirs

    - name: Скопировать dot-файлы
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: '{{ ansible_user_dir }}/'
        mode: 0644
      loop:
        - .editorconfig
      tags:
        - files

    - name: Установить/обновить минимальный набор пакетов
      ansible.builtin.package:
        name:
          - curl
          - git
          - traceroute
          - jq
          - make
          - net-tools
          - pipx
          - tree
          - wireguard{{ '-tools' if ansible_os_family == 'RedHat' }}
          - wl-clipboard
          - xsel
        state: present
      become: true
      tags:
        - minipack

    - name: Настроить SSH-клиент
      ansible.builtin.copy:
        content: |
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
          # #  Managed by Ansible                                                     # #
          # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

          # Завершать ssh-сессию, если сервер недоступен дольше 5 минут
          Host *
            ServerAliveInterval 1m
            ServerAliveCountMax 5
        dest: '{{ ansible_user_dir }}/.ssh/config'
        mode: 0644
      tags:
        - ssh

    - name: Настроить дистрибутив {{ ansible_distribution }}
      ansible.builtin.include_tasks:
        file: '{{ item }}'
        apply:
          tags:
            - distr
      with_first_found:
        - files:
            - tasks/distr_{{ ansible_distribution | lower }}.yml
          skip: true
      tags:
        - distr

    # https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key
    # https://docs.gitlab.com/ee/user/project/repository/ssh_signed_commits/
    - name: Настроить git на подписывание всех коммитов SSH-ключом пользователя
      community.general.git_config:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        state: present
        scope: global
      loop:
        - {key: gpg.format, value: ssh}
        - {key: user.signingKey, value: ~/.ssh/id_ed25519}
        - {key: commit.gpgSign, value: 'true'}
      tags:
        - git

    - name: Trial
      ansible.builtin.debug:
        msg: '{{ plugins | rejectattr("name", "eq", "romkatv/powerlevel10k") }}'
      tags:
        - trial

    - name: Trial 2
      ansible.builtin.set_fact:
        _fff: '{{ _fff | rejectattr("name", "eq", item.value) }}'
      vars:
        _fff: '{{ plugins }}'
      loop: '{{ _prompts | dict2items }}'
      tags:
        - trial2

    - name: Trial 2 add
      ansible.builtin.set_fact:
        _fff: '{{ [{"name": _prompts[prompt]}] + _fff }}'
      tags:
        - trial2

    - name: Trial 2 print
      ansible.builtin.debug:
        var: _fff
      tags:
        - trial2

  roles:

    - {role: cli_analogs, tags: [cli_analogs]}

    - {role: fonts, tags: [fonts]}

    - role: fzf
      vars:
        default_command: fd --type f --hidden --exclude .git
        default_options: --border --height=30% --info=inline --layout=reverse --bind=tab:down  # подробнее: man fzf
      tags:
        - fzf

    - {role: keyd, tags: [keyd]}

    - role: locale
      vars:
        formats: ru_RU.UTF-8
        language: en_US.UTF-8
      tags:
        - locale

    - role: zsh
      vars:
        zsh_home_subdir: '{{ ZSH_HOME_SUBDIR }}'
        aliases:
          df: df -h
          du: du -h
          e: $EDITOR
          la: ls -h -A --group-directories-first
          ll: ls -h -AlF --group-directories-first
          ping: ping -c4
          se: sudoedit
        aliases_global:
          L: '| less'
          G: '| grep'
          H: '| head'
          T: '| tail'
        default_editor: vim
        plugins:
          - name: zdharma/fast-syntax-highlighting
          - name: romkatv/powerlevel10k
          - name: zsh-users/zsh-autosuggestions
          - name: zsh-users/zsh-completions
          - name: belak/zsh-utils
            path: completion
          - name: Aloxaf/fzf-tab  # всегда должен быть последним в списке плагинов
      tags:
        - zsh
