---
- name: Настройка Linux-окружения
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: min

  vars:
    # Подкаталог в домашнем каталоге пользователя для всех конфигурационных файлов оболочки zsh
    ZSH_HOME_SUBDIR: .config/zsh

  environment:
    # Переменная окружения ZSHRC_DIR используется в ролях, устанавливающих свои zsh-скрипты
    # инициализации. Её значение устанавливается в роли zsh, но при первом запуске плейбука
    # эта переменная еще недоступна. Поэтому устанавливается здесь вручную.
    ZSHRC_DIR: ~/{{ ZSH_HOME_SUBDIR }}/zshrc.d

  pre_tasks:

    - name: Установить часовой пояс
      community.general.timezone:
        name: Asia/Novokuznetsk
      become: true
      tags:
        - timezone

    - name: Создать мои каталоги
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/{{ item }}'
        state: directory
        mode: 0700
      loop:
        - 1clouds  # синхронизируемые с облаками файлы
        - 1git     # все git-репозитории, кроме dotfiles
        - 1temp    # временные файлы, которые "не жалко"
      tags:
        - dirs

    - name: Скопировать dot-файлы
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: '{{ ansible_user_dir }}/'
      loop:
        - .editorconfig
      tags:
        - files

    - name: Установить/обновить минимальный набор пакетов
      ansible.builtin.package:
        name:
          - curl
          - git
          - traceroute
          - jq
          - make
          - net-tools
          - pipx
          - tree
          - xsel
        state: present
      become: true
      tags:
        - minipack

    - name: Настроить SSH-клиент
      ansible.builtin.copy:
        content: |
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
          # #  Managed by Ansible                                                     # #
          # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

          # Завершать ssh-сессию, если сервер недоступен дольше 5 минут
          Host *
            ServerAliveInterval 1m
            ServerAliveCountMax 5
        dest: '{{ ansible_user_dir }}/.ssh/config'
        mode: 0644
      tags:
        - ssh

    - name: Настроить дистрибутив {{ ansible_distribution }}
      ansible.builtin.include_tasks:
        file: '{{ item }}'
        apply:
          tags:
            - distr
      with_first_found:
        - files:
            - tasks/distr_{{ ansible_distribution | lower }}.yml
          skip: true
      tags:
        - distr

  roles:

    - { role: cli_analogs, tags: [cli_analogs] }

    - { role: fonts, tags: [fonts] }

    - role: fzf
      vars:
        default_command: fd --type f --hidden --exclude .git
        default_options: --border --height=30% --info=inline --layout=reverse --bind=tab:down  # подробнее: man fzf
      tags:
        - fzf

    - { role: keyd, tags: [keyd] }

    - role: locale
      vars:
        formats: ru_RU.UTF-8
        language: en_US.UTF-8
      tags:
        - locale

    - role: zsh
      vars:
        zsh_home_subdir: '{{ ZSH_HOME_SUBDIR }}'
        plugins:
          - name: Aloxaf/fzf-tab
            type: light
          - name: zsh-users/zsh-autosuggestions
            type: light
          - name: zdharma/fast-syntax-highlighting
            type: light
          - name: romkatv/powerlevel10k
            type: light
            ices:
              - name: depth
                value: 1
      tags:
        - zsh
