---
- name: Настройка Linux-окружения
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: min

  pre_tasks:

    - name: Установить часовой пояс
      community.general.timezone:
        name: Asia/Novokuznetsk
      become: true
      tags:
        - timezone

    - name: Скопировать dot-файлы
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: '{{ ansible_user_dir }}/'
      loop:
        - .editorconfig
      tags:
        - files

    - name: Установить/обновить минимальный набор пакетов
      ansible.builtin.package:
        name:
          - curl
          - git
          - traceroute
          - jq
          - make
          - net-tools
          - pipx
          - tree
          - xsel
        state: present
      become: true
      tags:
        - minipack

    - name:
      ansible.builtin.copy:
        content: |
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
          # #  Managed by Ansible                                                     # #
          # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
          # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

          # Завершать ssh-сессию, если сервер недоступен дольше 5 минут
          Host *
            ServerAliveInterval 1m
            ServerAliveCountMax 5
        dest: '{{ ansible_user_dir }}/.ssh/config'
        mode: 0644
      tags:
        - ssh

    - name: Создать каталог 'ws' (workspace) для работы
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/ws'
        state: directory
        mode: 0750
      tags:
        - files

  roles:

    - { role: keyd, tags: [keyd] }
    - { role: fonts, tags: [fonts] }

    - role: zsh
      vars:
        plugins:
          - name: Aloxaf/fzf-tab
            type: light
          - name: zsh-users/zsh-autosuggestions
            type: light
          - name: zdharma/fast-syntax-highlighting
            type: light
          - name: romkatv/powerlevel10k
            type: light
            ices:
              - name: depth
                value: 1
      tags:
        - zsh

    - { role: cli_analogs, tags: [cli_analogs] }

    - role: fzf
      vars:
        default_command: fd --type f --hidden --strip-cwd-prefix --exclude .git
        default_options: --border --height=30% --info=inline --layout=reverse --bind=tab:down  # подробнее: man fzf
      tags:
        - fzf

    - { role: vim, tags: [vim] }
    - { role: ranger, tags: [ranger] }

    - role: radimih.docker
      vars:
        daemon_json_extra:
          # Docker Registry в офисной VPN-сети
          insecure-registries:
            - 172.17.21.6:4444
            - 172.17.21.6:2222
          registry-mirrors:
            - http://172.17.21.6:4444
      tags:
        - docker

    - role: xssh
      vars:
        connections_dir: '{{ ansible_user_dir }}/.ssh/connections'
      tags:
        - xssh
