---
- name: Настройка Linux-окружения
  hosts:
    - desktop
    - servers

  tasks:

    - name: Установить часовой пояс
      community.general.timezone:
        name: Asia/Novokuznetsk
      become: true
      tags:
        - timezone

    - name: Скопировать dot-файлы
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: '{{ ansible_user_dir }}/'
      loop:
        - .editorconfig
        - .gitconfig
      tags:
        - files

    - name: Установить/обновить минимальный набор пакетов
      ansible.builtin.apt:
        name:
          - curl
          - inetutils-traceroute
          - net-tools
          - tree
        state: latest
        update_cache: true
        cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
      become: true
      tags:
        - minipack

- name: Настройка Desktop-окружения
  hosts:
    - desktop

  pre_tasks:

    - name: Установить/обновить минимальный набор пакетов для Desktop
      ansible.builtin.apt:
        name:
          - git
          - httpie
          - jq
          - make
          - pipx
          - ripgrep
          - xsel
        state: latest
        update_cache: true
        cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
      become: true
      tags:
        - minipack

  roles:

    - { role: keyd, tags: [keyd] }
    - { role: fonts, tags: [fonts] }

    - role: zsh
      vars:
        plugins:
          - name: zsh-users/zsh-autosuggestions
            type: light
          - name: marlonrichert/zsh-autocomplete
            type: light
          - name: zdharma/fast-syntax-highlighting
            type: light
          - name: romkatv/powerlevel10k
            type: light
            ices:
              - name: depth
                value: 1
      tags:
        - zsh

    - { role: vim, tags: [vim] }
    - { role: ranger, tags: [ranger] }

    - role: docker
      vars:
        daemon_json_extra:
          # Docker Registry в офисной VPN-сети
          insecure-registries:
            - 172.17.21.6:4444
            - 172.17.21.6:2222
          registry-mirrors:
            - http://172.17.21.6:4444
      tags:
        - docker

    - { role: annotator, tags: [annotator] }

    - role: remmina
      vars:
        # Каталог, где хранятся файлы-профили соединений. Будет создан, если не существует.
        # Ограничения со стороны SNAP:
        #   - должен располагаться внутри home-каталога пользователя
        #   - в пути не должен встречаться "скрытый" каталог (с точкой в начале имени каталога)
        connections_dir: '{{ ansible_user_dir }}/snap/remmina/common/connections'
        options:
          disable_tray_icon: 'true'
          prevent_snap_welcome_message: 'true'
          view_file_mode: 1
        secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36646335306633363036393562326663353732346366383638373231333236303939333263623265
          3835623939643038313262623833363036653735343133310a353732613866363732396466383938
          38353063386532653936316561303333343466653664346236393734626235303063393965613633
          3563653662626537390a363230363238376538383936323837303139343632343535663363353266
          35643639363662653161396465636664336664353165383139653430333837633963353633373363
          6534376230643831383362346230383961613863633764323661
      tags:
        - remmina
