# Внимание! При использовании модуля community.general.dconf необходимо соблюдать следующие правила:
#
#  * Все строковые значения должны обязательно обрамляться в кавычки, иначе будет выводиться ошибка.
#  * Кавычки для строковых значений должны обязательно быть ОДИНАРНЫМИ, иначе таска всегда будет
#    иметь статус changed == true, даже если значение фактически не поменялось.

---
- name: Настройка GNOME Shell
  hosts:
    - desktop

  pre_tasks:

    - name: Установить python-модуль psutil для работы ansible-модуля community.general.dconf
      ansible.builtin.apt:
        name: python3-psutil
        state: present
      become: true

    - name: Установить Gnome Tweaks
      ansible.builtin.apt:
        name: gnome-tweaks
        state: present
      become: true

    - name: Установить следование фокуса окна за мышью
      community.general.dconf:
        key: /org/gnome/desktop/wm/preferences/focus-mode
        value: "'sloppy'"
        state: present

    - name: Установить раскладки клавиатуры us,ru
      community.general.dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us'), ('xkb', 'ru')]"
        state: present

    - name: Установить циклический переключатель раскладок клавиатуры в Shift-RightCtrl
      community.general.dconf:
        key: /org/gnome/desktop/wm/keybindings/switch-input-source
        value: "['<Shift>Control_R']"
        state: present

    - name: Установить wallpaper
      community.general.dconf:
        key: /org/gnome/desktop/background/{{ item.key }}
        value: "'{{ item.value | string }}'"
        state: present
      loop:
        - { key: color-shading-type, value: solid }
        - { key: picture-options, value: zoom }
        - { key: picture-uri, value: 'file://{{ ansible_user_dir }}/dotfiles/wallpapers/cold-coast.jpg' }
        - { key: primary-color, value: '#000000' }
        - { key: secondary-color, value: '#000000' }
      tags:
        - wallpaper

    # # Тема "Plata" (https://gitlab.com/tista500/plata-theme) рекомендована автором
    # # расширения Material Shell

    # - name: Установить PPA-репозиторий темы
    #   ansible.builtin.apt_repository:
    #     repo: ppa:tista/plata-theme
    #     state: present
    #   become: true

    # - name: Установить apt-пакет темы
    #   ansible.builtin.apt:
    #     name: plata-theme
    #     state: latest
    #     update_cache: true
    #     cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
    #   become: true

    #   # GNOME Tweaks / Appearance / Themes / Applications
    # - name: Установить выбранную тему текущей Applications-темой
    #   community.general.dconf:
    #     key: /org/gnome/desktop/interface/gtk-theme
    #     value: "'Plata-Compact'"
    #     state: present

    #   # GNOME Tweaks / Appearance / Themes / Shell (требуется включенное расширение "User Themes"
    #   # https://extensions.gnome.org/extension/19/user-themes/)
    # - name: Установить выбранную тему текущей Shell-темой
    #   community.general.dconf:
    #     key: /org/gnome/shell/extensions/user-theme/name
    #     value: "'Plata-Compact'"
    #     state: present

  roles:

    # Посмотреть какие параметры были изменены в самом приложении:
    #   dconf dump /org/gnome/terminal/legacy/

    - name: Настроить GNOME Terminal
      role: gnome_terminal
      vars:
        keybindings:
          copy: <Primary>c
          paste: <Primary>v
        options:
          background-color: rgb(0,43,54)      # Solarized dark
          foreground-color: rgb(131,148,150)  # Solarized dark
          background-transparency-percent: 9
          font: Iosevka Term Light 12
          use-system-font: false
          use-theme-colors: false
          use-theme-transparency: false
          use-transparent-background: true
      tags:
        - terminal

    - name: Установить GNOME-расширение для переключения раскладок клавиатуры с помощью программы gdbus
      role: gnome_extension_LayoutSwitchAPI
      tags:
        - layout_extension

    # Посмотреть текущие привязки:
    #   dconf dump /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/
    # Посмотреть какие из них включены:
    #   dconf read /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings

    - name: Определить кастомные клавиатурные привязки (все предыдущие удаляются)
      role: gnome_custom_keybindings
      vars:
        key_bindings:
          - name: Layout English
            binding: '<Primary><Shift>F11'  # Ctrl+Shift+F11
            command: gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/LayoutSwitchAPI --method org.gnome.Shell.LayoutSwitchAPI.Switch us
          - name: Layout Russian
            binding: '<Primary><Shift>F12'  # Ctrl+Shift+F12
            command: gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/LayoutSwitchAPI --method org.gnome.Shell.LayoutSwitchAPI.Switch ru
          - name: Terminal
            binding: '<Super>t'
            command: gnome-terminal
      tags:
        - keybindings

    - name: Установить расширения с сайта https://extensions.gnome.org/
      role: gnome_extensions
      vars:
        ids:
          - 3357  # Material Shell (https://extensions.gnome.org/extension/3357/material-shell/)
          - 4727  # Primary Input on LockScreen (https://extensions.gnome.org/extension/4727/primary-input-on-lockscreen/)
          - 4839  # Clipboard History (https://extensions.gnome.org/extension/4839/clipboard-history/)
      tags:
        - extensions

  post_tasks:

    # Посмотреть текущие настройки GNOME-расширений:
    #   dconf dump /org/gnome/shell/extensions/

    - block:

      - name: Настроить GNOME-расширение Material Shell
        community.general.dconf:
          key: /org/gnome/shell/extensions/materialshell/theme/surface-opacity
          value: 70
          state: present

      - name: Настроить GNOME-расширение Clipboard History
        community.general.dconf:
          key: /org/gnome/shell/extensions/clipboard-history/{{ item.key }}
          value: '{{ item.value }}'
          state: present
        loop: '{{ options | dict2items }}'
        vars:
          options:
            toggle-menu: "['<Control>F10']"
            prev-menu: "['<Control>F11']"
            next-menu: "['<Control>F12']"

      tags:
        - extensions
