---
- name: Установка GUI-приложений
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  roles:

    - role: flameshot
      vars:
        options:
          showDesktopNotification: 'false'
          showHelp: 'false'
          showStartupLaunchMessage: 'false'
      tags:
        - flameshot

    - { role: telegram, tags: [telegram] }
    - { role: vscode, tags: [vscode] }
    - { role: zoom, tags: [zoom] }
