---
- name: Настройка моего стандартного Linux-окружения
  hosts: localhost

  roles:
    - {role: minipack, tags: ['minipack']}
    - {role: fonts, tags: ['fonts']}
    - {role: keyboard, tags: ['keyboard']}
    - {role: docker, tags: ['docker']}
    - {role: joplin, tags: ['joplin']}
    - {role: pipx, tags: ['pipx']}
    - {role: remmina, tags: ['remmina']}
    - role: zsh
      vars:
        zinit_plugins:
          - name: zsh-users/zsh-autosuggestions
            type: light
          - name: zdharma/fast-syntax-highlighting
            type: light
      tags:
        - zsh
    - {role: dev-python, tags: ['dev', 'python']}
