---
- name: Настройка моего стандартного Linux-окружения
  hosts: localhost

  roles:
    - {role: minipack, tags: ['minipack']}
    - {role: fonts, tags: ['fonts']}
    - {role: remmina, tags: ['remmina']}
    - role: zsh
      vars:
        zinit_plugins:
          - name: plugin/test1
            type: load
            ices:
              - lucid
              - wait
          - name: plugin/test2
            type: load
          - name: plugin/test3
            type: light
            ices:
              - lucid
              - wait
              - name: atinit
                value: >-
                  AAA=B;
                  BBB=C
          - name: plugin/test4
            type: light
            ices:
              - lucid
              - wait
              - name: atinit
                value: DDD
              - name: atinit
                value: FFF
              - name: atinit
                value: GGG
              - name: atinit
                value: YYY
          - name: plugin/test5
            type: snippet
      tags:
        - zsh
