---
- name: Настройка моего стандартного Linux-окружения
  hosts:
    - desktop
    - servers

  tasks:

    - name: Установить/обновить минимальный набор пакетов
      become: true
      apt:
        name:
          - curl
          - inetutils-traceroute
          - net-tools
          - tree
        state: latest
        update_cache: true
        cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
      tags:
        - minipack

- name: Настройка моего стандартного Desktop-окружения
  hosts:
    - desktop

  pre_tasks:

    - name: Установить/обновить минимальный набор пакетов для Desktop
      become: true
      apt:
        name:
          - git
          - httpie
          - jq
          - pipx
          - python3-pip
          - ripgrep
          - xsel
        state: latest
        update_cache: true
        cache_valid_time: 7200  # apt update если кэш не обновлялся более 2 часов
      tags:
        - minipack

  roles:

    - {role: fonts, tags: ['fonts']}

    - role: gnome
      vars:
        extensions_ids:
          - 19    # User Themes (https://extensions.gnome.org/extension/19/user-themes/)
          - 277   # Impatience (https://extensions.gnome.org/extension/277/impatience/)
          - 779   # Clipboard Indicator (https://extensions.gnome.org/extension/779/clipboard-indicator/)
          - 3357  # Material Shell (https://extensions.gnome.org/extension/3357/material-shell/)
      tags:
        - gnome

    - {role: keyboard, tags: ['keyboard']}
    - {role: docker, tags: ['docker']}
    - {role: vim, tags: ['vim']}
    - {role: flameshot, tags: ['flameshot']}
    - {role: ranger, tags: ['ranger']}
    - {role: joplin, tags: ['joplin']}
    - {role: pipx, tags: ['pipx']}
    - {role: dev-python, tags: ['dev', 'python']}

    - role: remmina
      vars:
        remmina_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36646335306633363036393562326663353732346366383638373231333236303939333263623265
          3835623939643038313262623833363036653735343133310a353732613866363732396466383938
          38353063386532653936316561303333343466653664346236393734626235303063393965613633
          3563653662626537390a363230363238376538383936323837303139343632343535663363353266
          35643639363662653161396465636664336664353165383139653430333837633963353633373363
          6534376230643831383362346230383961613863633764323661
      tags:
        - remmina

    - role: zsh
      vars:
        zinit_plugins:
          - name: zsh-users/zsh-autosuggestions
            type: light
          - name: marlonrichert/zsh-autocomplete
            type: light
          - name: zdharma/fast-syntax-highlighting
            type: light
          - name: romkatv/powerlevel10k
            type: light
            ices:
              - name: depth
                value: "1"
      tags:
        - zsh
