---
- name: Настройка моего стандартного Linux-окружения
  hosts: localhost

  roles:
    - {role: minipack, tags: ['minipack']}
    - {role: fonts, tags: ['fonts']}
    - {role: remmina, tags: ['remmina']}
