---
- name: radimih.docker
  src: https://github.com/radimih/ansible-role-docker.git
  scm: git
  version: v1.0.0

- name: radimih.github_latest
  src: https://github.com/radimih/ansible-role-github-latest.git
  scm: git
  version: v1.0.0

- name: radimih.zsh
  src: https://github.com/radimih/ansible-role-zsh.git
  scm: git
  version: v1.1
