---
- name: radimih.docker
  src: https://github.com/radimih/ansible-role-docker.git
  scm: git

- name: radimih.github_latest
  src: https://github.com/radimih/ansible-role-github-latest.git
  scm: git
