# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vm-desktop"

  config.vm.box = "fedora-37-workstation"
  config.vm.box_url = "file://#{Dir.home()}/ws/virtual-machines/boxes/fedora-37-workstation.json"

  config.vm.provider "virtualbox" do |v|
    v.name = "fedora-37-workstation"
    v.gui = true
    v.memory = 4096
    v.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    v.customize ["setextradata", :id, "GUI/Fullscreen", "on"]
    v.customize ["setextradata", :id, "GUI/MiniToolBarAlignment", "top"]
  end

  config.vm.synced_folder "../", "/home/vagrant/dotfiles"

  config.vm.provision "init", type: "shell" do |shell|
    shell.inline = "cd dotfiles; ./install-ansible.sh"
    shell.privileged = false
  end

  config.vm.provision "general", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook general.yml"
    shell.privileged = false
  end

  config.vm.provision "gnome", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook gnome.yml"
    shell.privileged = false
  end

  config.vm.provision "gui-apps", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook gui-apps.yml"
    shell.privileged = false
  end

  config.vm.provision "tui-apps", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook tui-apps.yml"
    shell.privileged = false
  end

end
