# -*- mode: ruby -*-
# vi: set ft=ruby :

distr = "fedora-38-workstation"
# distr = "ubuntu-22.04-desktop"

Vagrant.configure("2") do |config|

  config.vm.define "vm-desktop"

  config.vm.box = distr
  config.vm.box_url = "file://#{Dir.home()}/1git/virtual-machines/boxes/#{distr}.json"

  config.vm.provider "virtualbox" do |v|
    v.name = "vm-for-dotfiles"
    v.gui = true
    v.memory = 4096
    v.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    v.customize ["setextradata", :id, "GUI/Fullscreen", "on"]
    v.customize ["setextradata", :id, "GUI/MiniToolBarAlignment", "top"]
  end

  config.vm.synced_folder "../", "/home/vagrant/dotfiles"

  config.vm.provision "init", type: "shell" do |shell|
    shell.inline = "cd dotfiles; ./install-ansible.sh"
    shell.privileged = false
  end

  config.vm.provision "general", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook general.yml"
    shell.privileged = false
  end

  config.vm.provision "gnome", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook gnome.yml -t terminal"
    shell.privileged = false
  end

  config.vm.provision "apps", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook apps.yml -t ranger"
    shell.privileged = false
  end

  config.vm.provision "test", type: "shell" do |shell|
    shell.env = {"ANSIBLE_BECOME_ASK_PASS" => "false"}
    shell.inline = "cd dotfiles/ansible; ansible-playbook dev-devops.yml"
    shell.privileged = false
  end

end
