# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vm-desktop"

  config.vm.box = "ubuntu-22.04-desktop"
  config.vm.box_url = "file://#{Dir.home()}/workspace/virtual-machines/boxes/ubuntu-22.04-desktop.json"

  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-22.04-desktop"
    v.gui = true
    v.memory = 4096
    v.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    v.customize ["setextradata", :id, "GUI/Fullscreen", "on"]
    v.customize ["setextradata", :id, "GUI/MiniToolBarAlignment", "top"]
  end

  config.vm.synced_folder "../", "/home/vagrant/dotfiles"

  config.vm.provision "general", type: "ansible_local" do |ansible|
    ansible.groups = {
      "desktop" => ["vm-desktop"]
    }
    ansible.playbook = "general.yml"
    ansible.tags = ["timezone", "files", "minipack", "keyd", "fonts", "zsh", "fzf", "vim", "ranger", "docker", "annotator"]
    ansible.verbose = false  # возможные значения: false, true (эквивалентно опции -v), "vvv", "vvvv"
  end

  config.vm.provision "gnome", type: "ansible_local" do |ansible|
    ansible.groups = {
      "desktop" => ["vm-desktop"]
    }
    ansible.playbook = "gnome.yml"
    ansible.verbose = false  # возможные значения: false, true (эквивалентно опции -v), "vvv", "vvvv"
  end

end
