---
- name: Добавить поддержку виртуализации
  hosts: 127.0.0.1
  connection: local

  roles:

    - name: apt_thirdparty_package
      vars:
        key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        repo_url: https://download.virtualbox.org/virtualbox/debian
        repo_component: contrib
        package_name: virtualbox-6.1
      when:
        - ansible_os_family == 'Debian'
      tags:
        - virtualbox

    - name: apt_thirdparty_package
      vars:
        key_url: https://apt.releases.hashicorp.com/gpg
        repo_url: https://apt.releases.hashicorp.com
        repo_component: main
        package_name: vagrant
      when:
        - ansible_os_family == 'Debian'
      tags:
        - vagrant

  post_tasks:

    # Стандартная команда vagrant autocomplete install довольно топорно прописывает
    # вызов autocompletion-скрипта в в конец скрипта ~/.bashrc
    # TODO: добавить autocompletion для zsh

    - name: Установить shell autocompletion для Vagrant
      vars:
        bash_completion_dir: /etc/bash_completion.d
      block:
        - name: Получить версию Vagrant
          ansible.builtin.shell:
            cmd: vagrant --version | cut -d' ' -f2
          register: r__vagrant_version
          changed_when: false

        - name: 'Версия Vagrant: {{ r__vagrant_version.stdout }}'
          ansible.builtin.set_fact:
            vagrant_version: '{{ r__vagrant_version.stdout }}'

        - name: Вычислить путь до autocompletion-скрипта
          ansible.builtin.set_fact:
            vagrant_completion_script: '/opt/vagrant/embedded/gems/{{ vagrant_version }}/gems/vagrant-{{ vagrant_version }}/contrib/bash/completion.sh'

        - name: Прописать autocompletion-скрипт в системе ({{ bash_completion_dir }}/)
          ansible.builtin.copy:
            content: |
              # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
              # #  Managed by Ansible                                                     # #
              # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
              # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
              [[ -e {{ vagrant_completion_script }} ]] && . {{ vagrant_completion_script }}
            dest: '{{ bash_completion_dir }}/vagrant'
          become: true
      tags:
        - autocompletion
        - vagrant
