---
- name: Добавить поддержку виртуализации
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: min

  roles:

    - role: apt_thirdparty_package
      vars:
        key_url: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt/gpg
        repo_url: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt
        # key_url: https://apt.releases.hashicorp.com/gpg
        # repo_url: https://apt.releases.hashicorp.com
        key_file: /usr/share/keyrings/hashicorp.asc  # расширение .asc, так как ключ, размещённый по ссылке, в ASCII-формате
        repo_component: main
        package_name: vagrant
      when:
        - ansible_os_family == 'Debian'
      tags:
        - vagrant

    - role: apt_thirdparty_package
      vars:
        key_url: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt/gpg
        repo_url: http://91.243.85.216:8080/banned-from-russia/hashicorp-apt
        # key_url: https://apt.releases.hashicorp.com/gpg
        # repo_url: https://apt.releases.hashicorp.com
        key_file: /usr/share/keyrings/hashicorp.asc  # расширение .asc, так как ключ, размещённый по ссылке, в ASCII-формате
        repo_component: main
        package_name: packer
      when:
        - ansible_os_family == 'Debian'
      tags:
        - packer

  post_tasks:

    # Стандартная команда vagrant autocomplete install довольно топорно прописывает
    # вызов autocompletion-скрипта в конец скриптов ~/.bashrc и ~/.zshrc

    - name: Установить shell autocompletion для Vagrant
      vars:
        bash_completion_dir: /etc/bash_completion.d
        zsh_completion_dir: /usr/share/zsh/vendor-completions
      block:
        - name: Получить версию Vagrant
          ansible.builtin.shell:
            cmd: vagrant --version | cut -d' ' -f2
          register: r__vagrant_version
          changed_when: false

        - name: 'Версия Vagrant: {{ r__vagrant_version.stdout }}'
          ansible.builtin.set_fact:
            vagrant_version: '{{ r__vagrant_version.stdout }}'

        - name: Вычислить пути до autocompletion-скриптов
          ansible.builtin.set_fact:
            vagrant_completion_script_bash: '/opt/vagrant/embedded/gems/{{ vagrant_version }}/gems/vagrant-{{ vagrant_version }}/contrib/bash/completion.sh'
            vagrant_completion_script_zsh: '/opt/vagrant/embedded/gems/{{ vagrant_version }}/gems/vagrant-{{ vagrant_version }}/contrib/zsh/_vagrant'

        - name: Прописать autocompletion-скрипт в системе для bash ({{ bash_completion_dir }}/)
          ansible.builtin.copy:
            content: |
              # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
              # #  Managed by Ansible                                                     # #
              # #  DO NOT EDIT THIS FILE MANUALLY                                         # #
              # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
              [[ -e {{ vagrant_completion_script_bash }} ]] && . {{ vagrant_completion_script_bash }}
            dest: '{{ bash_completion_dir }}/vagrant'
            mode: 0644
          become: true
          tags:
            - bash

        - name: Прописать autocompletion-скрипт в системе для zsh ({{ zsh_completion_dir }}/)
          ansible.builtin.copy:
            src: '{{ vagrant_completion_script_zsh }}'
            dest: '{{ zsh_completion_dir }}'
            mode: 0644
          become: true
          tags:
            - zsh
      tags:
        - autocompletion
        - vagrant
