---
- name: Добавить поддержку виртуализации
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: [min]

  tasks:

    # https://docs.fedoraproject.org/en-US/quick-docs/virtualization-getting-started/
    # https://developer.fedoraproject.org/tools/vagrant/vagrant-libvirt.html
    - name: Для RedHat/Fedora
      when:
        - ansible_os_family is defined
        - ansible_os_family | lower == 'redhat'
      become: true
      block:

        # dnf groupinfo virtualization
        - name: Установить KVM, QEMU, libvirt, libvirt-manager, libvirt-viewer
          ansible.builtin.dnf:
            name: '@virtualization'
            state: present

        - name: Start libvirtd
          ansible.builtin.systemd:
            service: libvirtd
            enabled: true
            state: started

        - name: Start virtnetworkd
          ansible.builtin.systemd:
            service: virtnetworkd
            enabled: true
            state: started

        # dnf groupinfo vagrant
        - name: Установить Vagrant, Vagrant-libvirt
          ansible.builtin.dnf:
            name: '@vagrant'
            state: present

        - name: Добавить пользователя '{{ ansible_user_id }}' в группу 'libvirt'
          ansible.builtin.user:
            name: '{{ ansible_user_id }}'
            groups: libvirt
            append: true

    # TODO: добавить shell-autocomplete из роли hashicorp
