---
- name: Добавить поддержку виртуализации
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  gather_subset: min

  roles:

    - { role: virtualbox, tags: [virtualbox] }

    - role: hashicorp
      vars:
        packages:
          - packer
          - vagrant
      tags:
        - hashicorp
