#!/usr/bin/env zsh

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

[ -s $HOME/.zinitrc ] && source $HOME/.zinitrc
