#!/usr/bin/env zsh

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

[ -s {{ ansible_env.HOME }}/.zinitrc ] && source {{ ansible_env.HOME }}/.zinitrc
