---
galaxy_info:
  author: Radimir Mikhailov
  description: Install pipx (https://github.com/pipxproject/pipx)
  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []
