---
- name: Получить недостающие факты о хосте
  ansible.builtin.setup:
    gather_subset: min
  when: ansible_os_family is not defined

- name: Добавить официальный репозиторий приложения
  ansible.builtin.include_tasks: add_repo_os_family_{{ ansible_os_family | lower }}.yml

- name: Установить пакет приложения
  ansible.builtin.package:
    name: virtualbox-7.0
    state: present
  become: true

# Чтобы в ВМ, запущенных пользователем ansible_user_id, были доступны USB-устройства
- name: Добавить пользователя '{{ ansible_user_id }}' в группу 'vboxusers'
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: vboxusers
    append: true
  become: true
