# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

alias cat='bat'
alias ls='exa'
alias ll='exa --oneline --all --group-directories-first --long --icons'
