# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

alias cat='bat'
alias ls='exa --icons --group-directories-first --time-style=long-iso'
alias la='ls  --all'
alias ll='ls  --all --oneline --long'
