# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #  Managed by Ansible                                                     # #
# #  DO NOT EDIT THIS FILE MANUALLY                                         # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

alias cat='bat'
alias ls='exa --icons --group-directories-first --time-style=long-iso'
alias la='ls  --all'
alias ll='ls  --all --oneline --long'
alias rg='rg --hidden --glob="!.git/" --max-columns=150'
