---
- name: Установить утилиту fc-cache
  become: yes
  apt:
    name: fontconfig
    state: present

- name: Скопировать шрифты в {{ fonts_dir }}
  become: yes
  copy:
    src: files/
    dest: "{{ fonts_dir }}"
    owner: root
    group: root
    mode: "644"
  notify: rebuild-fonts-cache
