---
- name: Установить утилиту fc-cache
  apt:
    name: fontconfig
    state: present
  become: true

- name: Скопировать шрифты в {{ _fonts_dir }}
  copy:
    src: files/
    dest: '{{ _fonts_dir }}'
    owner: root
    group: root
    mode: 0644
  become: true
  notify: rebuild-fonts-cache
