---
- name: Установить python-модуль psutil для работы ansible-модуля community.general.dconf
  ansible.builtin.apt:
    name: python3-psutil
    state: present
  become: true

- name: Установить служебные пакеты
  ansible.builtin.apt:
    name:
      - gnome-shell-extensions
      - chrome-gnome-shell
    state: present
  become: true

- name: Получить версию GNOME Shell
  ansible.builtin.shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r__gnome_version
  changed_when: false

- name: 'Версия GNOME Shell: {{ r__gnome_version.stdout }}'
  ansible.builtin.set_fact:
    gnome_shell_version: '{{ r__gnome_version.stdout }}'

- name: Получить информацию по устанавливаемым расширениям
  ansible.builtin.uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}
    return_content: true
  loop: '{{ ids }}'
  register: r__extensions_info

- name: Создать временный каталог для загрузки расширений
  ansible.builtin.tempfile:
    state: directory
    suffix: .extensions_download
  register: r__extensions_download_dir
  changed_when: false

- block:

  - name: Установить расширения
    include_tasks: install_extension.yml
    vars:
      extension_info: '{{ item.json }}'
    loop: '{{ r__extensions_info.results }}'

  always:
    - name: Удалить временный каталог для загрузки расширений
      ansible.builtin.file:
        path: '{{ r__extensions_download_dir.path }}'
        state: absent
      changed_when: false
